import { Injectable }               from '@angular/core';

import { AddReferenceComponent }    from './add-reference.component';
import { ButtonComponent }          from './button.component';
import { CheckboxComponent }        from './checkbox.component';
import { HiddenComponent }          from './hidden.component';
import { InputComponent }           from './input.component';
import { MessageComponent }         from './message.component';
import { NoneComponent }            from './none.component';
import { NumberComponent }          from './number.component';
import { RadiosComponent }          from './radios.component';
import { RootComponent }            from './root.component';
import { SectionComponent }         from './section.component';
import { SelectComponent }          from './select.component';
import { SelectFrameworkComponent } from './select-framework.component';
import { TabComponent }             from './tab.component';
import { TabsComponent }            from './tabs.component';
import { TextareaComponent }        from './textarea.component';
import { ListComponent }            from './list.component';
import {MaterialDesignLibraryService} from '../material-design-framework/material-design.service';



@Injectable()
export class WidgetsService {

  defaultWidget: string = 'string';
  private activeFramework: string = 'none';
  widgetLibrary: any = {

    // Angular JSON Schema Form administrative widgets
    'none': NoneComponent, // Placeholder, for development - displays nothing
    'root': RootComponent, // Form root, renders a complete layout
    'select-framework': SelectFrameworkComponent, // Applies the selected framework to a specified widget
    '$ref': AddReferenceComponent, // Button to add a new array item or $ref element

    // Free-form text HTML 'input' form control widgets <input type="...">
    'email': 'text',
    'integer': 'number', // Note: 'integer' is not a recognized HTML input type
    'number': NumberComponent,
    'password': 'text',
    'search': 'text',
    'tel': 'text',
    'text': InputComponent,
    'string': InputComponent,
    'url': 'text',

    // Controlled text HTML 'input' form control widgets <input type="...">
    'color': 'text',
    'date': 'text',
    'datetime': 'text',
    'datetime-local': 'text',
    'month': 'text',
    'range': 'number',
    'time': 'text',
    'week': 'text',

    // Non-text HTML 'input' form control widgets <input type="...">
    // 'button': <input type="button"> not used, use <button> instead
    'checkbox': CheckboxComponent, // TODO: Set ternary = true for 3-state ??
    'hidden': 'text',
    'image': 'text', // TODO: Figure out how to handle these
    'radio': 'radios',
    'reset': 'submit', // TODO: Figure out how to handle these
    'submit': ButtonComponent,

    // Other (non-'input') HTML form control widgets
    'button': ButtonComponent,
    'select': SelectComponent,
    // 'optgroup': TODO: automatically generated by select widgets (how?)
    // 'option': automatically generated by select widgets
    'textarea': TextareaComponent,

    // HTML form control widget sets
    'radios': RadiosComponent, // Grouped list of radio buttons
    'radios-inline': 'radios', // Radio controls in one line
    'radiobuttons': 'radios', // Radio controls as html buttons

    // HTML Layout widgets
    // 'label': automatically added to data widgets
    // 'legend': automatically added to fieldsets
    'section': SectionComponent, // Just a div <div>
    'div': 'section', // Still just a div <div>
    'fieldset': 'section', // A fieldset, with an optional legend <fieldset>
    'flex': 'section', // A flexbox container <div style="display: flex">

    // Non-HTML layout widgets
    'array': 'section', // A list you can add, remove and reorder <fieldset>
    'tabarray': 'tabs', // A tabbed version of array
    'tab': TabComponent, // A tab group, similar to a fieldset or section <fieldset>
    'tabs': TabsComponent, // A tabbed set of panels with different controls
    'message': MessageComponent, // Insert arbitrary html
    'help': 'message', // Insert arbitrary html
    'msg': 'message', // Insert arbitrary html
    'html': 'message', // Insert arbitrary html

    // Widgets included for compatibility with JSON Form API
    'advancedfieldset': 'section', // Adds 'Advanced settings' title <fieldset>
    'authfieldset': 'section', // Adds 'Authentication settings' title <fieldset>
    'optionfieldset': 'section', // Option control, displays selected sub-item <fieldset>
    'selectfieldset': 'section', // Select control, displays selected sub-item <fieldset>
    'conditional': 'section', // Identical to 'section' (depeciated) <div>
    'actions': 'section', // Horizontal button list, can only submit, uses buttons as items <div>
    'tagsinput': 'section', // For entering short text tags <div>
    // See: http://ulion.github.io/jsonform/playground/?example=fields-checkboxbuttons

    // Widgets included for compatibility with React JSON Schema Form API
    'updown': 'number',
    'date-time': 'text',
    'alt-datetime': 'text',
    'alt-date': 'text',

    // Widgets included for compatibility with Angular Schema Form API
    'wizard': 'section', // TODO: Sequential panels with "Next" and "Previous" buttons
    'list': ListComponent

  };
  registeredWidgets: any = { };
  frameworkWidgets: any = { };
  activeWidgets: any = { };
  //allFrameWorks: any = {};

  constructor(public material: MaterialDesignLibraryService) {
    this.setActiveWidgets();
    //this.setToAllFrameWorks(this.material.frameworkName, this.material.widgetLibrary);
    this.setFrameWork(this.material.frameworkName, this.material.widgetLibrary);
  }

  /*setToAllFrameWorks(name, library){
    this.allFrameWorks[name] = library;
  }*/

  setFrameWork(name, library){
    this.frameworkWidgets[name] = library;
  }

  setActiveWidgetsByFrameWorkName(frameWorkName) {
    this.activeWidgets = Object.assign(
      { }, this.widgetLibrary, this.frameworkWidgets[frameWorkName], this.registeredWidgets
    );
    this.changeRefActiveWidgetsToComponent();
  }

  changeRefActiveWidgetsToComponent(){
    for (let widgetName of Object.keys(this.activeWidgets)) {
      let widget: any = this.activeWidgets[widgetName];
      // Resolve aliases
      if (typeof widget === 'string') {
        let usedAliases: string[] = [];
        while (typeof widget === 'string' && usedAliases.indexOf(widget) === -1) {
          usedAliases.push(widget);
          widget = this.activeWidgets[widget];
        }
        if (typeof widget !== 'string') {
          this.activeWidgets[widgetName] = widget;
        }
      }
    }
  }


  setActiveWidgets() {
    this.activeWidgets = Object.assign(
      { }, this.widgetLibrary, this.frameworkWidgets, this.registeredWidgets
    );
    this.changeRefActiveWidgetsToComponent();
  }

  setDefaultWidget(type: string): boolean {
    if (!this.hasWidget(type)) { return false; }
    this.defaultWidget = type;
    return true;
  }

  hasWidget(type: string, widgetSet: string = 'activeWidgets'): boolean {
    if (!type || typeof type !== 'string') { return false; }
    return this[widgetSet].hasOwnProperty(type);
  }

  hasDefaultWidget(type: string): boolean {
    return this.hasWidget(type, 'widgetLibrary');
  }

  registerWidget(type: string, widget: any): boolean {
    if (!type || !widget || typeof type !== 'string') { return false; }
    this.registeredWidgets[type] = widget;
    this.setActiveWidgets();
    return true;
  }

  unRegisterWidget(type: string): boolean {
    if (!type || typeof type !== 'string' ||
      !this.registeredWidgets.hasOwnProperty(type)) { return false; }
    delete this.registeredWidgets[type];
    this.setActiveWidgets();
    return true;
  }

  unRegisterAllWidgets(unRegisterFrameworkWidgets: boolean = true): boolean {
    this.registeredWidgets = { };
    if (unRegisterFrameworkWidgets) { this.frameworkWidgets = { }; }
    this.setActiveWidgets();
    return true;
  }

  registerFrameworkWidgets(widgets: any): boolean {
    if (widgets === null || typeof widgets !== 'object') { return false; }
    this.frameworkWidgets = widgets;
    this.setActiveWidgets();
    return true;
  }

  unRegisterFrameworkWidgets(): boolean {
    if (Object.keys(this.frameworkWidgets).length) {
      this.frameworkWidgets = { };
      this.setActiveWidgets();
    }
    return true;
  }

  getWidget(type?: string, widgetSet: string = 'activeWidgets'): any {
    if (this.hasWidget(type, widgetSet)) {
      return this[widgetSet][type];
    } else if (this.hasWidget(this.defaultWidget, widgetSet)) {
      return this[widgetSet][this.defaultWidget];
    } else {
      return null;
    }
  }

  getAllWidgets(): any {
    return {
      widgetLibrary: this.widgetLibrary,
      registeredWidgets: this.registeredWidgets,
      frameworkWidgets: this.frameworkWidgets,
      activeWidgets: this.activeWidgets,
    };
  }
}
